### ISSUE TITLE
problems with SSL host verification with proxy servers

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/Downloads.jl#108]
Multiple people in the last few hours have reported problems downloading artifacts on Windows systems using proxy servers: [here](https://discourse.julialang.org/t/julia-1-6-new-package-manager-curl-firewall-problems/58021) and [here](https://discourse.julialang.org/t/julia-1-6-using-curl-behind-proxy-for-artifacts-downloads-on-windows/58029).   In both cases, a workaround was `ENV["JULIA_SSL_NO_VERIFY_HOSTS"] = "github.com"`.

Given how quickly this popped up after the 1.6 release, I'm guessing that this will be a common problem, so I'm filing this issue to keep track of progress on tracking down the source of the problem and fixing it.

**Comment by lrnv** [comment]
For the record, i want to say that setting `http_proxy` and `https_proxy` as environnement variables is also necessary. This can be done before launching julia in a shell, or direlty in Julia; My `startup.jl` got updated with: 

```
ENV["http_proxy"] = "http://<your_proxy>:<port>"
ENV["https_proy"] = "http://<your_proxy>:<port>"
ENV["JULIA_SSL_NO_VERIFY_HOSTS"] = "github.com"
```

**Comment by StefanKarpinski** [comment]
It's unclear to me that there's anything wrong here. [This post](https://discourse.julialang.org/t/julia-1-6-new-package-manager-curl-firewall-problems/58021/22) is my best understanding of the issue. It seems like what's going on here is that people are on Windows machines behind MITM proxies that are not configured to allow Windows CRL check requests. The configuration that works is to configure the proxy via the `http_proxy` and `https_proxy` variables and to tell `libcurl` not to try to verify hosts with the `JULIA_SSL_NO_VERIFY_HOSTS` variable. We could turn certificate revocation checking off, but that's insecure. We could have an option to turn revocation checking off without disabling host verification altogether, but since this is only a problem when you're behind a MITM firewall that will be presenting fake certificates for verification anyway, that's not actually any more secure than just turning verification off altogether. There seem to be two solutions here:

1. Tell IT to configure their MITM proxy/firewall so that it handles Windows CRL requests;
2. Barring that, tell end users to `export JULIA_SSL_NO_VERIFY_HOSTS="**"`.

Note that the `https?_proxy` setting is only necessary for non-transparent proxies. At many organizations, the proxy is transparent and you don't have to do that but the `JULIA_SSL_NO_VERIFY_HOSTS` may still be necessary.

**Comment by lrnv** [comment]
I agree I'm not sure that anything can be done here, apart from pointing users having these issues to right right configuration parameters. 

Behavior or snooping IT departments is, sadly, not open to pull requests ATM.

**Comment by StefanKarpinski** [comment]
This issue should be mitigated by https://github.com/JuliaLang/Downloads.jl/pull/115, which switches `Downloads` to using best effort CRL checking instead of failing if the firewall prevents the CRL check from getting through. This is now included in Downloads 1.4.1 which is used on the Julia 1.6 release branch, so should be included in Julia 1.6.2 when it is released. If you could potentially try a Julia 1.6 nightly or build the release-1.6 branch from source and see if it solves this problem, that would be great. Otherwise, we'll see if this issue is resolved in the 1.6.2 release when it comes out.

**Comment by lrnv** [comment]
On Julia 1.6.0 and Downloads 1.4.1, it works correctly for me, but i still have to set `ENV["JULIA_SSL_NO_VERIFY_HOSTS"] = "github.com"`.
But it also did before the change to Downloads, so i'm not sure about the result.

**Comment by decoherencer** [comment]
> For the record, i want to say that setting `http_proxy` and `https_proxy` as environnement variables is also necessary. This can be done before launching julia in a shell, or directly in Julia (since no shell is attached to a julia session by default on windows); My `startup.jl` got updated with:
> 
> ```
> ENV["http_proxy"] = "http://<your_proxy>:<port>"
> ENV["https_proy"] = "http://<your_proxy>:<port>"
> ENV["JULIA_SSL_NO_VERIFY_HOSTS"] = "github.com"
> ```
> 
> where the proxy values are the same as the ones in your `.gitconfig`.

Thank you

**Comment by StefanKarpinski** [comment]
Closing this, assuming it's been fixed.

**Comment by lewisl** [comment]
Not fixed on MacOS v 12.0.1 as of Nov. 9, 2021.

I am not using a Proxy Server.

**Comment by StefanKarpinski** [comment]
If you're not using a proxy, then it can't be the same issue. If you could open a new issue describing the different problem you're having then perhaps we could debug it. If you could also provide necessary debugging info like your Julia version, that would be helpful.

**Comment by lewisl** [comment]
You are correct. An unrelated problem with some similar messages. 

I've removed conda installed python and re-installed Julia. My issue was conflicting artifacts for QT5.  Removing Python from within ~/.julia eliminates the duplication. GR brings In the only artifact for QT. 

New Mac environments result in some challenges for Python, too.
