### ISSUE TITLE
`download()` multi-thread error

### ISSUE THREAD

**Issue by Moelf** [JuliaLang/Downloads.jl#110]
on:
```
Julia Version 1.6.0
Commit f9720dc2eb (2021-03-24 12:55 UTC)
```

```
julia> imgs = [
       "https://images.unsplash.com/photo-1554266183-2696fdafe3ff?ixlib=rb-1.2.1&auto=format&fit=crop&w=564&q=80"
       "https://images.unsplash.com/photo-1527026950045-9e066846bae4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1419&q=80"
       "https://images.unsplash.com/photo-1549287748-f095932c9f81?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=606&q=80"
       "https://images.unsplash.com/photo-1437448317784-3a480be9571e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=634&q=80"
       ]

julia> imgs = repeat(imgs, 4)

julia> Threads.nthreads()
4

julia> Threads.@threads for url in imgs
           download(url)
       end
```

results in
```
ERROR: TaskFailedException
Stacktrace:
 [1] wait
   @ ./task.jl:317 [inlined]
 [2] threading_run(func::Function)
   @ Base.Threads ./threadingconstructs.jl:34
 [3] top-level scope
   @ ./threadingconstructs.jl:93

    nested task error: TaskFailedException
    Stacktrace:
      [1] try_yieldto(undo::typeof(Base.ensure_rescheduled))
```

also seen in another occation:
```
Error: curl_multi_socket_action: 8
```

**Comment by StefanKarpinski** [comment]
Yeah, something definitely isn't threadsafe. Will look into it.

**Comment by fredrikekre** [comment]
Here is the nested task error which might shed some more light:
```
        nested task error: val already in a list
        Stacktrace:
          [1] error(s::String)
            @ Base ./error.jl:33
          [2] push!
            @ ./linked_list.jl:53 [inlined]
          [3] wait(c::Base.GenericCondition{Base.Threads.SpinLock})
            @ Base ./condition.jl:103
          [4] lock(rl::ReentrantLock)
            @ Base ./lock.jl:100
          [5] lock(f::Downloads.Curl.var"#39#41"{Int32, Downloads.Curl.Multi}, l::ReentrantLock)
            @ Base ./lock.jl:185
          [6] event_callback(uv_poll_p::Ptr{Nothing}, status::Int32, events::Int32)
            @ Downloads.Curl ~/julia16/usr/share/julia/stdlib/v1.6/Downloads/src/Curl/Multi.jl:120
```

**Comment by anandijain** [comment]
I have little to add, but that I am also getting this. Is the temporary solution to just never call `@threads ... download(...) end`?

https://github.com/anandijain/SBMLBioModelsRepository.jl/runs/2335985628?check_suite_focus=true#step:5:2330 Is a link to a full trace/crash happening on CI

**Comment by StefanKarpinski** [comment]
This should be fixed but there's also no need to do multithreaded downloading — you can just use tasks:
```jl
@sync for url in imgs
    @async @show download(url)
end
```

**Comment by c42f** [comment]
Reading https://curl.se/libcurl/c/threadsafe.html it seems there could be several things we're not doing:

* We should call `curl_global_init` explicitly as part of libcurl `__init__`
* We probably need to set locking and unlocking callbacks using `curl_share_setopt` in order that libcurl itself can protect its internal connection pool and DNS cache. See https://curl.se/libcurl/c/curl_share_setopt.html
* The page says "You must never share the same handle in multiple threads", but we share the multi handle. It's behind our own lock so that might be ok, but multiple easy handles are created from that multi handle — it's unclear from the docs whether they will then point to shared multi handle data structures and implicitly need locking as well.

**Comment by c42f** [comment]
To add to this, libcurl has a known bug where it can't share the connection pool between multiple threads. See https://curl.se/libcurl/c/curl_share_setopt.html#CURLLOCKDATACONNECT.

The following PR removed the libcurl example which showed how to use shared connection pools (due to this bug) but it's interesting nonetheless: https://github.com/curl/curl/pull/6795

Unfortunately I think this libcurl bug combines quite badly with the task migration introduced in julia-1.7. A set of tasks which share a connection pool should also be running on the same OS thread, but the Julia runtime can now migrate those tasks at any time. We can't disable sharing of the connection pool either - that would be a performance disaster in the normal `@async` case.

**Comment by StefanKarpinski** [comment]
We could potentially do all libcurl calls from a single thread, but I'm not sure that we have a mechanism to do that anymore since all tasks can be migrated now? The API calls could just dispatch to a single thread that does the actual libcurl stuff. Since libcurl doesn't actually benefit from multithreading at all, it would be fine.

**Comment by c42f** [comment]
Excellent, I've been meaning to do some performance tests of this kind of thing.

What was the typical file size for the data you're requesting, and what kind of bandwidth can you hit if you use a standalone downloader like `rclone` or `s5cmd`?

**Comment by ericphanson** [comment]
I think Kolia was working with larger files, but I had ~380k 20 kB files. I put 100k of them in a prefix `test_cache_path` to make it easier to use s5cmd.

I get (using Downloads.jl)
```julia
using AWSS3, AWS
AWS.DEFAULT_BACKEND[] = AWS.DownloadsBackend()
paths = readdir(test_cache_path)
all_bytes, t = @timed asyncmap(read, paths)
throughput = (sum(length, all_bytes)*8)/(t*1e9)
@info "Pulled down $(Base.format_bytes(sum(length, all_bytes))) bytes in $(round(t; digits=1)) seconds for a throughput of $(round(throughput; sigdigits=3)) Gbps (gigabits per second)"
```
using (bits/ns == gigabits/s), I get
```julia
[ Info: Pulled down 1.837 GiB bytes in 145.0 seconds for a throughput of 0.109 Gbps (gigabits per second)
```

I couldn't figure out a good way to read them in bulk into memory with `s5cmd` (seems like `cat` doesn't support wildcards, so I guess the right way is to write out a file with my 100k paths and use a `run`?) so I tried just writing them to disk. With 100k such files in a prefix `test_cache_path`, just doing
```julia
_, s5cmd_time = @timed read(`s5cmd cp $(test_cache_path)\* /tmp/s5cmd`)
throughput = (sum(length, all_bytes)*8)/(s5cmd_time*1e9)
@info "Pulled down $(Base.format_bytes(sum(length, all_bytes))) bytes in $(round(s5cmd_time; digits=1)) seconds for a throughput of $(round(throughput; sigdigits=3)) Gbps (gigabits per second)"
```
gives
```julia
[ Info: Pulled down 1.837 GiB bytes in 97.9 seconds for a throughput of 0.161 Gbps (gigabits per second)
```

So faster, but also not good. But I wonder how much is the cost of the disk IO -- since we skip that in the Julia case we should be able to be pretty fast. (That's also my actual use-case-- pulling cached data directly into ram, skipping disk IO).

**Comment by kolia** [comment]
I was getting 2.4Gps downloading 23k files of size ~2 - 4Mb each.

**Comment by c42f** [comment]
> I couldn't figure out a good way to read them in bulk into memory with s5cmd

You could use a ramdisk (mount type `tmpfs`) to avoid any disk overhead. `/dev/shm` is usually mounted as `tmpfs` so you could create the files in there.

> So faster, but also not good.

But if Downloads.jl can come close to the performance of `s5cmd` (or whatever else is regarded to be the fastest concurrent downloader) then we should be in reasonable shape.

**Comment by mkschulze** [comment]
Hello, just leaving a note here, that we would also like to see threadsafety with libcurl/downloads.jl. We use it extensively within our TypeDBClient.jl (gRPCClient.jl as transaction layer) and it would be great to have it being able to use multithreading. Shall we post an example of our usecase and where we would need it?

**Comment by StefanKarpinski** [comment]
After some back and forth, the version on master here as well as Julia master should be threadsafe. Closing since that's the case and we can open specific issues about more fine-grained threading problems as they're encountered.
