### ISSUE TITLE
Downloading files from SourceForge gets an HTML error page

### ISSUE THREAD

**Issue by giordano** [JuliaLang/Downloads.jl#37]
Julia v1.5
```
julia> dir = mktempdir()
"/tmp/jl_f42CqU"

julia> url = "https://sourceforge.net/projects/libpng/files/libpng16/1.6.37/libpng-1.6.37.tar.gz"
"https://sourceforge.net/projects/libpng/files/libpng16/1.6.37/libpng-1.6.37.tar.gz"

julia> download(url, joinpath(dir, basename(url)))
"/tmp/jl_f42CqU/libpng-1.6.37.tar.gz"
```
correctly downloads the archive, while
```
julia> Downloads.download(url, joinpath(dir, basename(url)))
"/tmp/jl_f42CqU/libpng-1.6.37.tar.gz"
```
gets an HTML error page from SourceForge.  Maybe it's a matter of setting the header correctly?

**Comment by StefanKarpinski** [comment]
Here's the situation:

* SourceForge supports HTTP/2 so the connection gets upgraded to that.

* HTTP/2 **mandates** that header keys be [lowercase only](https://stackoverflow.com/questions/54067796/preserving-case-of-http-headers-with-curl), the wording is quite strict:
  > Just as in HTTP/1.x, header field names are strings of ASCII characters that are compared in a case-insensitive fashion.  However, header field names MUST be converted to lowercase prior to their encoding in HTTP/2.  A request or response containing uppercase header field names MUST be treated as malformed.

* SourceForge, in violation of the spec for both HTTP/1 and HTTP/2, considers header key case significant and only replies to requests with a `User-Agent` header—which it is a violation of the HTTP/2 spec to send.

* Prior to version 7.67.0, curl was [buggy](https://github.com/curl/curl/issues/4400) in that it incorrectly sent HTTP/2 headers in whatever case you provided them. This bug was fixed in version 7.67.0.

This means that any compliant HTTP/2 client cannot be used to download things from SourceForge, including recent versions of curl. In conclusion: SourceForge is an absolute trash fire.

It seems like the only viable option is to force using HTTP/1 for talking to SourceForge.

**Comment by StefanKarpinski** [comment]
I tried forcing this to HTTP/1.1 and discovered that I was wrong: it's not the `User-Agent` thing. Instead, it's that SourceForge refuses to serve software bundles if there is a `Referrer` header set. I guess we can turn off the auto-referrer setting.

**Comment by fingolfin** [comment]
Any chance for a new release of Downkoads.jl with this fix in?

**Comment by giordano** [comment]
For use in Yggdrasil this needs to go into julia nightly. I don't know if that happened again

**Comment by StefanKarpinski** [comment]
I'm working on [completing and stabilizing the API](https://github.com/JuliaLang/Downloads.jl/pull/46), at which point I'll make a 1.0 release.

**Comment by fingolfin** [comment]
Thing is that this blocks JLLs which are sourced from SourceForge

**Comment by giordano** [comment]
Now that I think about it, for the time being we don't use `Downloads.jl` in Yggdrasil

**Comment by fingolfin** [comment]
Ahh, OK. Then of course my comment is irrelevant.
